// src/components/App.vue
<script>
import Editor from './Editor.vue'
import Help from './Help.vue'
import LanguageSelector from './LanguageSelector.vue'
import NoteSelector from './NoteSelector.vue'
import StatusBar from './StatusBar.vue'
import TopNav from './TopNav.vue'
import RenameNote from './RenameNote.vue'
import ToastUndo from './ToastUndo.vue'
import Loading from './Loading.vue'
import History from "./History.vue"

import Settings from './settings/Settings.vue'
import { isAltNumEvent, setURLHashNoReload, stringSizeInUtf8Bytes, sleep } from '../util'
import { createNewScratchNote, createNoteWithName, dbDelDirHandle, deleteNote, getNotesMetadata, getMetadataForNote, getStorageFS, pickAnotherDirectory, switchToStoringNotesOnDisk, kScratchNoteName, canDeleteNote, renameNote, isSystemNoteName, kDailyJournalNoteName, kHelpSystemNoteName, kReleaseNotesSystemNoteName, preLoadAllNotes } from '../notes'
import { getModChar, getAltChar } from "../../src/util"
import ContextMenu from '@imengyu/vue3-context-menu'
import { supportsFileSystem, openDirPicker } from '../fileutil'
import { onOpenSettings, getSettings, onSettingsChange, setSetting } from '../settings'
import { boot } from '../webapp-boot'
import { getLanguage, langSupportsFormat, langSupportsRun } from '../editor/languages'
import { useToast, POSITION } from "vue-toastification";
import { exportNotesToZip } from '../notes-export'
import { logAppExit, logAppOpen, logNoteOp } from '../log'

/** @typedef {import("@imengyu/vue3-context-menu/lib/ContextMenuDefine").MenuItem} MenuItem */

let toastOptions = {
  position: POSITION.TOP_RIGHT,
  timeout: 4000,
  closeOnClick: true,
  pauseOnFocusLoss: true,
  pauseOnHover: true,
  // draggable: true,
  // draggablePercent: 0.6,
  showCloseButtonOnHover: false,
  hideProgressBar: true,
  closeButton: "button",
  icon: false,
  rtl: false
};

export default {
  components: {
    ContextMenu,
    Editor,
    Help,
    LanguageSelector,
    NoteSelector,
    History,
    RenameNote,
    Settings,
    StatusBar,
    TopNav,
    ToastUndo,
    Loading
  },

  setup() {
    const toast = useToast();
    return { toast }
  },

  data() {
    let settings = getSettings()
    // console.log("setting:", settings)
    return {
      column: 1,
      development: window.location.href.indexOf("dev=1") !== -1,
      docSize: 0,
      helpAnchor: "",
      language: "plaintext",
      languageAuto: true,
      line: 1,
      noteName: settings.currentNoteName,
      selectionSize: 0,
      settings: settings,
      showingHelp: false,
      showingMenu: false,
      showingLanguageSelector: false,
      showingNoteSelector: false,
      showingSettings: false,
      showingRenameNote: false,
      showingHistorySelector: false,
      theme: settings.theme,
      isSpellChecking: false,
      spellcheckToastID: 0,
      altChar: getAltChar(),
      loadingNoteName: "",
    }
  },

  mounted() {
    console.log("App.vue mounted")
    onSettingsChange((settings) => {
      this.settings = settings;
      this.theme = settings.theme;
      //throwIf(this.noteName != settings.currentNoteName, "noteName != settings.currentNoteName")
      console.log(`onSettingsChange callback, noteName: ${this.noteName}, settings.currentNoteName: ${settings.currentNoteName}, theme: ${this.theme}`)
    })
    onOpenSettings(() => {
      this.showingSettings = true
    })
    this.getEditor().setSpellChecking(this.isSpellChecking)
    window.addEventListener("keydown", this.onKeyDown)

    window.addEventListener("beforeunload", async () => {
      logAppExit(); // TODO: not sure if this async func will complete
      await this.getEditor().saveCurrentNote();
    });
    logAppOpen();

    if (false) {
      // testing of loadingNoteName dialog
      setTimeout(
        () => {
          this.loadingNoteName = "foo"
          setTimeout(
            () => {
              this.loadingNoteName = ""
            },
            2000
          )
        },
        1000
      )
    }
  },

  beforeUnmount() {
    window.removeEventListener("keydown", this.onKeyDown);
  },

  computed: {
    isShowingDialog() {
      return this.showingHelp || this.showingHistorySelector || this.showingLanguageSelector || this.showingMenu || this.showingRenameNote || this.showingNoteSelector || this.showingSettings
    },

    noteShortcut() {
      let name = this.noteName;
      let m = getMetadataForNote(name)
      if (m && m.altShortcut) {
        return `${this.altChar} + ${m.altShortcut}`
      }
      return ""
    },

    noteNameStatusBar() {
      let name = this.noteName
      let s = this.noteShortcut;
      if (s) {
        name = `${name} (${s})`
      }
      return name
    },

    mcStyle() {
      return {
        display: this.showingMenu ? "block" : "none"
      }
    },
  },

  methods: {
    /**
     * @returns {Editor}
    */
    getEditor() {
      // @ts-ignore
      return this.$refs.editor
    },

    toggleSpellCheck() {
      this.isSpellChecking = !this.isSpellChecking
      this.getEditor().setSpellChecking(this.isSpellChecking)
      // if (this.isSpellChecking) {
      //   this.toast("Press Shift + right mouse click for context menu when spell checking is enabled", toastOptions)
      // }
    },

    async openNote(name, skipSave = false) {
      console.log("App.openNote:", name)
      let editor = this.getEditor();
      editor.editor.setReadOnly(true);
      this.loadingNoteName = name
      await editor.openNote(name, skipSave);
      // await sleep(400);
      this.loadingNoteName = ""
      editor.focus()
    },

    /**
     * @param {KeyboardEvent} event
     */
    onKeyDown(event) {

      if (event.key === "Escape") {
        if (this.isShowingDialog) {
          return;
        }
        event.preventDefault()
        event.stopImmediatePropagation()
        this.openHistorySelector()
        return
      }

      // if (event.key === "F2") {
      //   console.log("F2");
      //   let undoAction = () => {
      //     console.log("undoAction")
      //   }
      //   this.toast({
      //     component: ToastUndo,
      //     props: {
      //       message: "F2 pressed",
      //       undoText: "Undo delete",
      //       undoAction: undoAction,
      //     },
      //   }, toastOptions)
      // }

      // TODO: can I do this better? The same keydown event that sets the Alt-N shortcut
      // in NoteSelector also seems to propagate here and immediately opens the note.
      if (!this.showingNoteSelector) {
        let altN = isAltNumEvent(event)
        // console.log("onKeyDown: e:", e, "altN:", altN)
        if (altN) {
          let meta = getNotesMetadata()
          for (let o of meta) {
            if (o.altShortcut == altN && o.name !== this.noteName) {
              // console.log("onKeyDown: opening note: ", o.name, " altN:", altN, " e:", e)
              this.openNote(o.name)
              event.preventDefault()
              return
            }
          }
        }
      }

      // hack: stop Ctrl + O unless it originates from code mirror (because then it
      // triggers NoteSelector.vue)
      if (event.key == "o" && event.ctrlKey && !event.altKey && !event.shiftKey) {
        let target = /** @type {HTMLElement} */ (event.target);
        let fromCodeMirror = target && target.className.includes("cm-content")
        if (!fromCodeMirror) {
          event.preventDefault()
        }
      }
    },

    onCloseRename() {
      this.showingRenameNote = false
      this.getEditor().focus()
    },

    async onRename(newName) {
      this.showingRenameNote = false
      let s = this.getEditor().getContent() || ""
      await renameNote(this.noteName, newName, s)
      await this.openNote(newName, true)
      console.log("onRename: newName:", newName)
    },

    onCloseHelp(e) {
      this.showingHelp = false
      this.getEditor().focus()
    },

    async storeNotesOnDisk() {
      let dh = await openDirPicker(true)
      if (!dh) {
        return;
      }
      // TODO: await this.getEditor().saveCurrentNote() ?
      await switchToStoringNotesOnDisk(dh);
      let settings = getSettings();
      await this.openNote(settings.currentNoteName, true)
    },

    async pickAnotherDirectory() {
      let ok = await pickAnotherDirectory();
      if (!ok) {
        return
      }
      await boot()
      await preLoadAllNotes()
    },

    async switchToBrowserStorage() {
      console.log("switchToBrowserStorage(): deleting dir handle")
      await dbDelDirHandle();
      await boot();
    },

    /**
     * @param {MouseEvent} e
     */
    onContextMenu(e) {
      if (this.showingNoteSelector || this.showingLanguageSelector || this.showingSettings || this.showingHelp) {
        return
      }
      // show native context menu if ctrl or shift is pressed
      // especially important for spell checking
      let forceNativeMenu = e.ctrlKey;
      if (forceNativeMenu) {
        return
      }

      let modChar = getModChar();
      let altChar = getAltChar();
      let theme = document.documentElement.getAttribute("theme")
      let menuTheme = "default"
      if (theme == "dark") {
        menuTheme = "default dark"
      }
      e.preventDefault();
      this.showingMenu = true
      let canDelete = this.canDeleteNote();
      /** @type {MenuItem[]} */
      let items = [
        {
          label: "Open / create / delete note",
          onClick: () => { this.openNoteSelector() },
          shortcut: `${modChar} + K`,
        },
        {
          label: "Note",
          children: [
            {
              label: "Rename current note",
              onClick: () => { this.renameCurrentNote() },
              disabled: !canDelete,
            },
            {
              label: "Delete current note",
              onClick: () => { this.deleteCurrentNote() },
              disabled: !canDelete,
            },
            {
              label: "Create new scratch note",
              onClick: () => { this.createNewScratchNote() },
              shortcut: `${altChar} + N`,
            },
          ]
        },
        {
          label: "Block",
          children: [
            {
              label: "And after current",
              onClick: () => { this.getEditor().addNewBlockAfterCurrent() },
              shortcut: `${modChar} + Enter`,
            },
            {
              label: "Add before current",
              onClick: () => { this.getEditor().addNewBlockBeforeCurrent() },
              shortcut: `${altChar} + Enter`,
            },
            {
              label: "Add at end",
              onClick: () => { this.getEditor().addNewBlockAfterLast() },
              shortcut: `${modChar} + Shift + Enter`,
            },
            {
              label: "Add at start",
              onClick: () => { this.getEditor().addNewBlockBeforeFirst() },
              shortcut: `${altChar} + Shift + Enter`,
            },
            {
              label: "Split at cursor position",
              onClick: () => { this.getEditor().insertNewBlockAtCursor() },
              shortcut: `${modChar} + ${altChar} + Enter`,
            },
            {
              label: "Goto next",
              onClick: () => { this.getEditor().gotoNextBlock() },
              shortcut: `${modChar} + Down`,
            },
            {
              label: "Goto previous",
              onClick: () => { this.getEditor().gotoPreviousBlock() },
              shortcut: `${modChar} + Up`,
            },
            {
              label: "Change language",
              onClick: () => { this.openLanguageSelector() },
              shortcut: `${modChar} + L`,
            },
            {
              label: "Select all text",
              onClick: () => { this.getEditor().selectAll() },
              shortcut: `${modChar} + A`,
            },
          ]
        },
        // TODO: set plain text, markdown
      ]
      let blockChildren = items[2].children
      let lang = getLanguage(this.language)
      if (langSupportsFormat(lang)) {
        blockChildren.push({
          label: "Format as " + this.language,
          onClick: () => { this.getEditor().formatCurrentBlock() },
          shortcut: `${altChar} + Shift + F`,
        })
      }
      if (langSupportsRun(lang)) {
        blockChildren.push({
          label: "Run " + this.language,
          onClick: () => { this.getEditor().runCurrentBlock() },
          shortcut: `${altChar} + Shift + R`,
        })
      }

      /** @type {MenuItem[]} */
      let children = [];
      let dh = getStorageFS();
      if (dh == null) {
        // if currently storing in browser
        children = [
          {
            label: "Current store: browser (localStorage)",
            disabled: true,
          }
        ]
      } else {
        children = [
          {
            label: `Current store: directory '${dh.name}'`,
            disabled: true,
          }
        ]
      }
      if (supportsFileSystem()) {
        if (dh === null) {
          children.push(
            {
              label: "Move notes from browser to directory",
              onClick: () => { this.storeNotesOnDisk() },
            }
          )
          children.push(
            {
              label: "Switch to notes in a directory",
              onClick: async () => { await this.pickAnotherDirectory() },
            }
          )
        } else {
          children.push(
            {
              label: "Switch to browser (localStorage)",
              onClick: async () => { await this.switchToBrowserStorage() },
            }
          )
          children.push(
            {
              label: "Switch to notes in a different directory",
              onClick: async () => { await this.pickAnotherDirectory() },
            }
          )
        }
      }
      children.push({
        label: "Export notes to .zip file",
        onClick: () => { this.exportNotesToZipFile() },
        divided: "up",
      })
      children.push({
        label: "Show help",
        onClick: () => { this.toggleHelp("storing-notes-on-disk") },
        divided: "up",
      })
      items.push({
        label: "Notes storage",
        children: children,
      })

      let s = this.isSpellChecking ? "Disable spell checking" : "Enable spell checking"
      items.push({
        label: s,
        onClick: () => {
          this.toggleSpellCheck();
        },
      })
      items.push({
        label: "Help",
        divided: "up",
        children: [
          {
            label: "Show help",
            onClick: () => { this.toggleHelp() },
          },
          {
            label: "Show help in new tab",
            onClick: () => { this.showHelpInNewTab() },
          },
          {
            label: "Show help as note",
            onClick: () => { this.showHelpAsNote() },
          },
          {
            label: "Release notes",
            onClick: () => { this.showReleaseNotes() },
          }
        ]
      })
      items.push({
        label: "Tip: Ctrl + click for native context menu",
        disabled: true,
      })
      ContextMenu.showContextMenu({
        x: e.x,
        y: e.y,
        theme: menuTheme,
        preserveIconWidth: false,
        keyboardControl: true,
        zIndex: 40,
        // @ts-ignore
        getContainer: () => {
          const o = this.$refs.menuContainer;
          // const o = document.body;
          return o
        },
        onClose: (lastClicked) => {
          // console.log("onClose: lastClicked:", lastClicked)
          this.showingMenu = false
          // this.getEditor().focus()
        },
        items: items,
      });

      // @ts-ignore
      this.$refs.menuContainer.focus()
    },

    exportNotesToZipFile() {
      exportNotesToZip()
    },

    onOpenSettings() {
      this.showingSettings = true
    },

    onCloseSettings() {
      this.showingSettings = false
      this.getEditor().focus()
    },

    onCursorChange(e) {
      this.line = e.cursorLine.line
      this.column = e.cursorLine.col
      this.selectionSize = e.selectionSize
      this.language = e.language
      this.languageAuto = e.languageAuto
    },

    renameCurrentNote() {
      console.log("renameNote:");
      this.showingRenameNote = true;
    },

    canDeleteNote() {
      let name = this.noteName
      if (name == "scratch" || name == "help") {
        return false
      }
      return true
    },

    async deleteCurrentNote() {
      let name = this.noteName
      console.log("deleteNote:", name);
      if (!canDeleteNote(name)) {
        console.log("cannot delete note:", name)
        return
      }
      await this.openNote(kScratchNoteName, true)
      await deleteNote(name)
      // TODO: add a way to undo deletion of the note
      this.toast(`Deleted note '${name}'`, toastOptions)
      logNoteOp("noteDelete")
    },

    async createNewScratchNote() {
      let name = await createNewScratchNote()
      await this.onOpenNote(name)
      // TODO: add a way to undo creation of the note
      this.toast(`Created scratch note '${name}'`, toastOptions)
      logNoteOp("noteCreate")
    },

    openLanguageSelector() {
      this.showingLanguageSelector = true
    },

    closeLanguageSelector() {
      this.showingLanguageSelector = false
      this.getEditor().focus()
    },

    onSelectLanguage(language) {
      this.showingLanguageSelector = false
      this.getEditor().setLanguage(language)
    },

    openHistorySelector() {
      this.showingHistorySelector = true
    },

    closeHistorySelector() {
      this.showingHistorySelector = false
      this.getEditor().focus()
    },

    onSelectHistory(name) {
      this.showingHistorySelector = false
      console.log("onSelectHistory:", name);
      this.openNote(name)
    },

    openNoteSelector() {
      this.showingNoteSelector = true
    },

    closeNoteSelector() {
      this.showingNoteSelector = false
      this.getEditor().focus()
      // console.log("closeNoteSelector")
    },

    /**
     * @param {string} name
     */
    onOpenNote(name) {
      this.showingNoteSelector = false
      this.openNote(name)
    },

    toggleHelp(anchor = "") {
      let willHide = this.showingHelp;
      if (willHide) {
        this.showingHelp = false;
        // this.getEditor().focus()
        return;
      }
      this.helpAnchor = anchor
      this.showingHelp = true
    },

    showHelpInNewTab() {
      // let uri = window.location.origin + "/help"
      window.open("/help", "_blank");
    },

    showHelpAsNote() {
      this.openNote(kHelpSystemNoteName);
    },

    showReleaseNotes() {
      this.openNote(kReleaseNotesSystemNoteName);
    },

    /**
     * @param {string} name
     */
    async onCreateNote(name) {
      this.showingNoteSelector = false
      await createNoteWithName(name)
      await this.onOpenNote(name)
      // TODO: add a way to undo creation of the note
      this.toast(`Created note '${name}'`, toastOptions)
      logNoteOp("noteCreate")
    },

    /**
     * @param {string} name
     */
    async onDeleteNote(name) {
      this.showingNoteSelector = false
      let settings = getSettings()
      // if deleting current note, first switch to scratch note
      // TODO: maybe switch to the most recently opened
      if (name === settings.currentNoteName) {
        console.log("deleted current note, opening scratch note")
        await this.openNote(kScratchNoteName)
      }
      // must delete after openNote() because openNote() saves
      // current note
      await deleteNote(name)
      this.getEditor().focus()
      console.log("deleted note", name)
      // TODO: add a way to undo deletion of the note
      this.toast(`Deleted note '${name}'`, toastOptions)
      logNoteOp("noteDelete")
    },

    /**
     * called when a new document has been loaded or when a document has been modified
     * TODO: maybe needs separate event onDocLoaded
     * @param {string} name
     */
    onDocChanged(name) {
      let justOpened = name !== undefined;
      // console.log(`doc changed: name: ${name} this.noteName: ${this.noteName}, justOpened: ${justOpened}`)
      if (name === undefined) {
        name = this.noteName
      } else {
        this.noteName = name
      }

      let editorComp = this.getEditor()
      const c = editorComp.getContent() || ""
      this.docSize = stringSizeInUtf8Bytes(c);

      if (justOpened) {
        console.log("onDocChanged: just opened")
        let readOnly = isSystemNoteName(name)
        editorComp.editor.setReadOnly(readOnly)
        if (name === kDailyJournalNoteName) {
          console.log("journal, so going to next block")
          editorComp.gotoNextBlock()
        }

        window.document.title = name;
        setURLHashNoReload(name)
        setSetting("currentNoteName", name);
      }
    },

    formatCurrentBlock() {
      this.getEditor().formatCurrentBlock()
      logNoteOp("noteFormatBlock")
    },

    runCurrentBlock() {
      this.getEditor().runCurrentBlock()
      logNoteOp("noteRunBlock")
    },
  },
}

</script>

<template>
  <div class="grid w-screen max-h-screen h-screen fixed grid-rows-[1fr_auto]" @contextmenu="onContextMenu($event)">
    <!--TODO: show note name, a drop-down for switching, search icon, menu -->
    <!-- <div class="text-base hidden">
      <div>{{ noteName }}</div>
      <div>23 notes</div>
    </div> -->
    <TopNav :noteName="noteName" :shortcut="noteShortcut" @openNoteSelector="openNoteSelector" />
    <Editor @cursorChange="onCursorChange" :theme="theme" :development="development" :debugSyntaxTree="false"
      :keymap="settings.keymap" :emacsMetaKey="settings.emacsMetaKey"
      :showLineNumberGutter="settings.showLineNumberGutter" :showFoldGutter="settings.showFoldGutter"
      :bracketClosing="settings.bracketClosing" :fontFamily="settings.fontFamily" :fontSize="settings.fontSize"
      class="overflow-hidden" ref="editor" @openLanguageSelector="openLanguageSelector"
      @openHistorySelector="openHistorySelector" @createNewScratchNote="createNewScratchNote"
      @openNoteSelector="openNoteSelector" @docChanged="onDocChanged" />
    <StatusBar :noteName="noteNameStatusBar" :line="line" :column="column" :docSize="docSize"
      :selectionSize="selectionSize" :language="language" :languageAuto="languageAuto"
      :isSpellChecking="isSpellChecking" @openLanguageSelector="openLanguageSelector"
      @openNoteSelector="openNoteSelector" @formatCurrentBlock="formatCurrentBlock" @runCurrentBlock="runCurrentBlock"
      @toggleSpellCheck="toggleSpellCheck" @openSettings="onOpenSettings" @toggleHelp="toggleHelp" class="" />
  </div>
  <div class="overlay">
    <LanguageSelector v-if="showingLanguageSelector" @selectLanguage="onSelectLanguage"
      @close="closeLanguageSelector" />
    <NoteSelector v-if="showingNoteSelector" @openNote="onOpenNote" @createNote="onCreateNote"
      @deleteNote="onDeleteNote" @close="closeNoteSelector" />
    <History v-if="showingHistorySelector" @close="closeHistorySelector" @selectHistory="onSelectHistory" />
    <Settings v-if="showingSettings" :initialSettings="settings" @close="onCloseSettings" />
  </div>
  <div :style="mcStyle" class="fixed inset-0 z-40 pointer-events-none">
    <form class="relative w-full h-full pointer-events-none z-50 text-[8px]" ref="menuContainer" tabIndex="-1"></form>
  </div>
  <Help @close="onCloseHelp" :anchor="helpAnchor" v-if="showingHelp" />
  <RenameNote @close="onCloseRename" @rename="onRename" :oldName="noteName" v-if="showingRenameNote" />

  <Loading :loadingNoteName="loadingNoteName" v-if="loadingNoteName" />
</template>

// src/components/App.svelte
<script>
  import RenameNote from "./RenameNote.svelte";
  import History from "./History.svelte";
  import NoteSelector from "./NoteSelector.svelte";
  import LanguageSelector from "./LanguageSelector.svelte";
  import Editor from "./Editor.svelte";
  import Loading from "./Loading.svelte";
  import StatusBar from "./StatusBar.svelte";
  import TopNav from "./TopNav.svelte";
  import Settings from "./Settings.svelte";
  import { getSettings, setSetting } from "../settings";
  import { logAppExit, logAppOpen, logNoteOp } from "../log";
  import {
    createNewScratchNote,
    createNoteWithName,
    dbDelDirHandle,
    deleteNote,
    getNotesMetadata,
    getMetadataForNote,
    getStorageFS,
    pickAnotherDirectory,
    switchToStoringNotesOnDisk,
    kScratchNoteName,
    canDeleteNote,
    renameNote,
    isSystemNoteName,
    kDailyJournalNoteName,
    kHelpSystemNoteName,
    kReleaseNotesSystemNoteName,
    preLoadAllNotes,
  } from "../notes";
  import {
    getAltChar,
    isAltNumEvent,
    setURLHashNoReload,
    stringSizeInUtf8Bytes,
    sleep,
    throwIf,
  } from "../util";
  import { getModChar } from "../../src/util";
  import { supportsFileSystem, openDirPicker } from "../fileutil";
  import { boot } from "../webapp-boot";
  import {
    getLanguage,
    langSupportsFormat,
    langSupportsRun,
  } from "../editor/languages";
  import { exportNotesToZip } from "../notes-export";
  import Toaster, { addToast } from "./Toaster.svelte";
  import Menu, {
    kMenuJustText,
    kMenuSeparator,
    kMenuStatusNormal,
    kMenuStatusRemoved,
  } from "../Menu.svelte";
  import Overlay from "./Overlay.svelte";

  let initialSettings = getSettings();

  let column = $state(1);
  let docSize = $state(0);
  let helpAnchor = $state("");
  let language = $state("plaintext");
  let languageAuto = $state(true);
  let line = $state(1);
  let noteName = $state(initialSettings.currentNoteName);
  let selectionSize = $state(0);
  let settings = $state(initialSettings);
  let showingMenu = $state(false);
  let showingLanguageSelector = $state(false);
  let showingNoteSelector = $state(false);
  let showingSettings = $state(false);
  let showingRenameNote = $state(false);
  let showingHistorySelector = $state(false);
  let isSpellChecking = $state(false);
  let spellcheckToastID = $state(0);
  let altChar = getAltChar();
  let loadingNoteName = $state("");

  let contextMenuStyle = $state(`left: 0px; top: 0px`);

  // /** @type {import("../editor/editor").EdnaEditor} */
  // let ednaEditor = $state(null);

  /** @type {Editor} */
  let editor;

  let isShowingDialog = $derived.by(() => {
    return (
      showingHistorySelector ||
      showingLanguageSelector ||
      showingMenu ||
      showingRenameNote ||
      showingNoteSelector ||
      showingSettings
    );
  });

  let noteShortcut = $derived.by(() => {
    let name = noteName;
    let m = getMetadataForNote(name);
    if (m && m.altShortcut) {
      return `${altChar} + ${m.altShortcut}`;
    }
    return "";
  });

  let mcStyle = $derived.by(() => {
    return {
      display: showingMenu ? "block" : "none",
    };
  });

  $effect(() => {
    getEditor().setSpellChecking(isSpellChecking);
    window.addEventListener("keydown", onKeyDown);

    window.addEventListener("beforeunload", async () => {
      logAppExit(); // TODO: not sure if this async func will complete
      await getEditor().saveCurrentNote();
    });
    logAppOpen();

    return () => {
      window.removeEventListener("keydown", onKeyDown);
    };
  });

  /**
   * @param {KeyboardEvent} event
   */
  function onKeyDown(event) {
    if (event.key === "Escape") {
      if (isShowingDialog) {
        return;
      }
      event.preventDefault();
      event.stopImmediatePropagation();
      openHistorySelector();
      return;
    }

    // if (event.key === "F2") {
    //   console.log("F2");
    //   let undoAction = () => {
    //     console.log("undoAction")
    //   }
    //   toast({
    //     component: ToastUndo,
    //     props: {
    //       message: "F2 pressed",
    //       undoText: "Undo delete",
    //       undoAction: undoAction,
    //     },
    //   }, toastOptions)
    // }

    // TODO: can I do this better? The same keydown event that sets the Alt-N shortcut
    // in NoteSelector also seems to propagate here and immediately opens the note.
    if (!showingNoteSelector) {
      let altN = isAltNumEvent(event);
      // console.log("onKeyDown: e:", e, "altN:", altN)
      if (altN) {
        let meta = getNotesMetadata();
        for (let o of meta) {
          if (o.altShortcut == altN && o.name !== noteName) {
            // console.log("onKeyDown: opening note: ", o.name, " altN:", altN, " e:", e)
            openNote(o.name);
            event.preventDefault();
            return;
          }
        }
      }
    }

    // hack: stop Ctrl + O unless it originates from code mirror (because then it
    // triggers NoteSelector.vue)
    if (event.key == "o" && event.ctrlKey && !event.altKey && !event.shiftKey) {
      let target = /** @type {HTMLElement} */ (event.target);
      let fromCodeMirror = target && target.className.includes("cm-content");
      if (!fromCodeMirror) {
        event.preventDefault();
      }
    }
  }

  async function storeNotesOnDisk() {
    let dh = await openDirPicker(true);
    if (!dh) {
      return;
    }
    // TODO: await getEditor().saveCurrentNote() ?
    await switchToStoringNotesOnDisk(dh);
    let settings = getSettings();
    await openNote(settings.currentNoteName, true);
  }

  async function pickAnotherDirectory2() {
    let ok = await pickAnotherDirectory();
    if (!ok) {
      return;
    }
    await boot();
    await preLoadAllNotes();
  }

  function exportNotesToZipFile() {
    exportNotesToZip();
  }

  function openSettings() {
    showingSettings = true;
  }

  function onCloseSettings() {
    showingSettings = false;
    getEditor().focus();
  }

  async function deleteCurrentNote() {
    let name = noteName;
    console.log("deleteNote:", name);
    if (!canDeleteNote(name)) {
      console.log("cannot delete note:", name);
      return;
    }
    await openNote(kScratchNoteName, true);
    await deleteNote(name);
    // TODO: add a way to undo deletion of the note
    addToast(`Deleted note '${name}'`);
    logNoteOp("noteDelete");
  }

  async function createScratchNote() {
    let name = await createNewScratchNote();
    await onOpenNote(name);
    // TODO: add a way to undo creation of the note
    addToast(`Created scratch note '${name}'`);
    logNoteOp("noteCreate");
  }

  async function switchToBrowserStorage() {
    console.log("switchToBrowserStorage(): deleting dir handle");
    await dbDelDirHandle();
    await boot();
  }

  function openNoteSelector() {
    showingNoteSelector = true;
  }

  function openLanguageSelector() {
    showingLanguageSelector = true;
  }

  let nextMenuID = 1000;
  function nmid() {
    nextMenuID++;
    return nextMenuID;
  }

  export const MENU_OPEN_NOTE = nmid();
  export const MENU_RENAME_CURRENT_NOTE = nmid();
  export const MENU_DELETE_CURRENT_NOTE = nmid();
  export const MENU_CREATE_SCRATCH_NOTE = nmid();
  export const MENU_BLOCK_AFTER_CURR = nmid();
  export const MENU_BLOCK_BEFORE_CURR = nmid();
  export const MENU_BLOCK_AT_END = nmid();
  export const MENU_BLOCK_AT_START = nmid();
  export const MENU_BLOCK_SPLIT_AT_CURSOR = nmid();
  export const MENU_BLOCK_GOTO_NEXT = nmid();
  export const MENU_BLOCK_GOTO_PREV = nmid();
  export const MENU_BLOCK_CHANGE_LANG = nmid();
  export const MENU_BLOCK_SELECTALL = nmid();
  export const MENU_BLOCK_FORMAT = nmid();
  export const MENU_BLOCK_RUN = nmid();
  export const MENU_TOGGLE_SPELL_CHECKING = nmid();
  export const MENU_HELP = nmid();
  export const MENU_HELP_AS_NOTE = nmid();
  export const MENU_HELP_RELEASE_NOTES = nmid();
  export const MENU_MOVE_NOTES_TO_DIRECTORY = nmid();
  export const MENU_SWITCH_TO_NOTES_IN_DIR = nmid();
  export const MENU_SWITCH_TO_LOCAL_STORAGE = nmid();
  export const MENU_EXPORT_NOTES = nmid();
  export const MENU_SHOW_EXPORT_HELP = nmid();

  function buildMenu() {
    let lang = getLanguage(language);

    const menuNote = [
      ["Rename current note", MENU_RENAME_CURRENT_NOTE],
      ["Delete current note", MENU_DELETE_CURRENT_NOTE],
      ["Create new scratch note\tAlt + N", MENU_CREATE_SCRATCH_NOTE],
    ];

    const menuBlock = [
      ["And after current\tMod + Enter", MENU_BLOCK_AFTER_CURR],
      ["Add before current\tAlt + Enter", MENU_BLOCK_BEFORE_CURR],
      ["Add at end\tMod + Shift + Enter", MENU_BLOCK_AT_END],
      ["Add at start\tAlt + Shift + Enter", MENU_BLOCK_AT_START],
      [
        "Split at cursor position\tMod + Alt + Enter",
        MENU_BLOCK_SPLIT_AT_CURSOR,
      ],
      ["Goto next\tMod + Down", MENU_BLOCK_GOTO_NEXT],
      ["Goto previous\tMod + Up", MENU_BLOCK_GOTO_PREV],
      ["Change language\tMod + L", MENU_BLOCK_CHANGE_LANG],
      ["Select all textMod + A", MENU_BLOCK_SELECTALL],
      ["Format as " + lang + "\tAlt + Shift + F", MENU_BLOCK_FORMAT],
      ["Run " + lang + "\tAlt + Shift + R", MENU_BLOCK_RUN],
    ];

    let dh = getStorageFS();
    let currStorage = "Current store: browser (localStorage)";
    if (dh) {
      currStorage = `Current store: directory ${dh.name}`;
    }
    const menuStorage = [
      [currStorage, kMenuJustText],
      ["Move notes from browser to directory", MENU_MOVE_NOTES_TO_DIRECTORY],
      ["Switch to browser (localStorage)", MENU_SWITCH_TO_LOCAL_STORAGE],
      ["Switch to notes in a directory", MENU_SWITCH_TO_NOTES_IN_DIR],
      kMenuSeparator,
      ["Export notes to .zip file", MENU_EXPORT_NOTES],
      kMenuSeparator,
      ["Show help", MENU_SHOW_EXPORT_HELP],
    ];

    const menuHelp = [
      ["Show help", MENU_HELP],
      ["Show help as note", MENU_HELP_AS_NOTE],
      ["Release notes", MENU_HELP_RELEASE_NOTES],
    ];

    let spelling = (isSpellChecking ? "Disable" : "Enable") + " spell checking";

    const contextMenu = [
      ["Open note\tMod + P", MENU_OPEN_NOTE],
      ["Note", menuNote],
      ["Block", menuBlock],
      ["Notes storage", menuStorage],
      [spelling, MENU_TOGGLE_SPELL_CHECKING],
      kMenuSeparator,
      ["Help", menuHelp],
      // ["Tip: Ctrl + click for native context menu", kMenuJustText],
    ];

    return contextMenu;
  }

  /**
   * @param {import("../Menu.svelte").MenuItem} mi
   */
  function menuItemStatus(mi) {
    let s = mi[0];
    let mid = mi[1];
    // console.log("menuItemStatus:", mi);
    // console.log("s:", s, "mid:", mid);
    let lang = getLanguage(language);
    let dh = getStorageFS();
    // console.log("dh:", dh);
    let hasFS = supportsFileSystem();
    if (mid === MENU_BLOCK_FORMAT) {
      if (!langSupportsFormat(lang)) {
        return kMenuStatusRemoved;
      }
    } else if (mid === MENU_BLOCK_RUN) {
      if (!langSupportsRun(lang)) {
        return kMenuStatusRemoved;
      }
    } else if (mid === MENU_MOVE_NOTES_TO_DIRECTORY) {
      if (!hasFS) {
        return kMenuStatusRemoved;
      }
      if (dh) {
        // currently using directory
        console.log("MENU_MOVE_NOTES_TO_DIRECTORY: removed\n");
        return kMenuStatusRemoved;
      }
      console.log("MENU_MOVE_NOTES_TO_DIRECTORY: not removed\n");
    } else if (mid == MENU_SWITCH_TO_LOCAL_STORAGE) {
      if (!hasFS) {
        return kMenuStatusRemoved;
      }
      if (dh === null) {
        // currently using local storage
        return kMenuStatusRemoved;
      }
    } else if (mid == MENU_SWITCH_TO_NOTES_IN_DIR) {
      if (!hasFS) {
        return kMenuStatusRemoved;
      }
    }
    return kMenuStatusNormal;
  }

  async function onmenucmd(cmdId, ev) {
    console.log("cmd:", cmdId);
    showingMenu = false;
    if (cmdId == MENU_OPEN_NOTE) {
      openNoteSelector();
    } else if (cmdId == MENU_RENAME_CURRENT_NOTE) {
      showingRenameNote = true;
    } else if (cmdId == MENU_DELETE_CURRENT_NOTE) {
      deleteCurrentNote();
    } else if (cmdId == MENU_CREATE_SCRATCH_NOTE) {
      createNewScratchNote();
    } else if (cmdId == MENU_BLOCK_AFTER_CURR) {
      getEditor().addNewBlockAfterCurrent();
    } else if (cmdId == MENU_BLOCK_BEFORE_CURR) {
      getEditor().addNewBlockBeforeCurrent();
    } else if (cmdId == MENU_BLOCK_AT_END) {
      getEditor().addNewBlockAfterLast();
    } else if (cmdId == MENU_BLOCK_AT_START) {
      getEditor().addNewBlockBeforeFirst();
    } else if (cmdId == MENU_BLOCK_SPLIT_AT_CURSOR) {
      getEditor().insertNewBlockAtCursor();
    } else if (cmdId == MENU_BLOCK_GOTO_NEXT) {
      getEditor().gotoNextBlock();
    } else if (cmdId == MENU_BLOCK_GOTO_PREV) {
      getEditor().gotoPreviousBlock();
    } else if (cmdId == MENU_BLOCK_CHANGE_LANG) {
      openLanguageSelector();
    } else if (cmdId == MENU_BLOCK_SELECTALL) {
      getEditor().selectAll();
    } else if (cmdId == MENU_BLOCK_FORMAT) {
      getEditor().formatCurrentBlock();
    } else if (cmdId == MENU_BLOCK_RUN) {
      getEditor().runCurrentBlock();
    } else if (cmdId == MENU_TOGGLE_SPELL_CHECKING) {
      toggleSpellCheck();
    } else if (cmdId == MENU_HELP) {
      showHelp();
    } else if (cmdId == MENU_HELP_AS_NOTE) {
      showHelpAsNote();
    } else if (cmdId == MENU_HELP_RELEASE_NOTES) {
      showReleaseNotes();
    } else if (cmdId == MENU_MOVE_NOTES_TO_DIRECTORY) {
      storeNotesOnDisk();
    } else if (cmdId == MENU_SWITCH_TO_NOTES_IN_DIR) {
      await pickAnotherDirectory();
    } else if (cmdId == MENU_SWITCH_TO_LOCAL_STORAGE) {
      await switchToBrowserStorage();
    } else if (cmdId == MENU_EXPORT_NOTES) {
      exportNotesToZipFile();
    } else if (cmdId == MENU_SHOW_EXPORT_HELP) {
      showHelp("#storing-notes-on-disk");
    } else {
      console.log("unknown menu cmd id");
    }
  }

  function closeMenu() {
    showingMenu = false;
    getEditor().focus();
  }

  let contextMenu = $state(null);
  /**
   * @param {MouseEvent} ev
   */
  function oncontextmenu(ev) {
    if (isShowingDialog) {
      return;
    }
    // show native context menu if ctrl or shift is pressed
    // especially important for spell checking
    let forceNativeMenu = ev.ctrlKey;
    if (forceNativeMenu) {
      return;
    }
    let { x, y } = ev;
    contextMenuStyle = `left: ${x}px; top: ${y}px;`;
    console.log("contextMenuStyle:", contextMenuStyle);
    ev.preventDefault();
    ev.stopImmediatePropagation();
    contextMenu = buildMenu();
    showingMenu = true;
  }

  /**
   * @returns {Editor}
   */
  function getEditor() {
    return editor;
  }

  function formatCurrentBlock() {
    getEditor().formatCurrentBlock();
    logNoteOp("noteFormatBlock");
  }

  function runCurrentBlock() {
    getEditor().runCurrentBlock();
    logNoteOp("noteRunBlock");
  }

  function toggleSpellCheck() {
    isSpellChecking = !isSpellChecking;
    getEditor().setSpellChecking(isSpellChecking);
    if (isSpellChecking) {
      addToast(
        "Press Shift + right mouse click for context menu when spell checking is enabled"
      );
    }
  }

  /**
   * @param {string} anchor
   */
  function showHelp(anchor = "") {
    // let uri = window.location.origin + "/help"
    let uri = "/help";
    if (anchor != "") {
      uri += anchor;
    }
    window.open(uri, "_blank");
  }

  function closeRename() {
    showingRenameNote = false;
    getEditor().focus();
  }

  function closeSettings() {
    console.log("closeSettings");
    showingSettings = false;
    getEditor().focus();
  }

  async function onRename(newName) {
    showingRenameNote = false;
    let s = getEditor().getContent() || "";
    await renameNote(noteName, newName, s);
    await openNote(newName, true);
    console.log("onRename: newName:", newName);
  }

  function openHistorySelector() {
    showingHistorySelector = true;
  }

  function closeHistorySelector() {
    showingHistorySelector = false;
    getEditor().focus();
  }

  function onSelectHistory(name) {
    showingHistorySelector = false;
    console.log("onSelectHistory:", name);
    openNote(name);
  }

  function onSelectLanguage(language) {
    showingLanguageSelector = false;
    getEditor().setLanguage(language);
  }

  function closeLanguageSelector() {
    showingLanguageSelector = false;
    getEditor().focus();
  }

  function closeNoteSelector() {
    showingNoteSelector = false;
    getEditor().focus();
  }

  async function openNote(name, skipSave = false) {
    console.log("App.openNote:", name);
    let editor = getEditor();
    editor.setReadOnly(true);
    loadingNoteName = name;
    await editor.openNote(name, skipSave);
    // await sleep(400);
    loadingNoteName = "";
    editor.focus();
  }

  /**
   * @param {string} name
   */
  function onOpenNote(name) {
    showingNoteSelector = false;
    openNote(name);
  }

  /**
   * @param {string} name
   */
  async function onCreateNote(name) {
    showingNoteSelector = false;
    await createNoteWithName(name);
    openNote(name);
    // TODO: add a way to undo creation of the note
    addToast(`Created note '${name}'`);
    logNoteOp("noteCreate");
  }

  /**
   * @param {string} name
   */
  async function onDeleteNote(name) {
    showingNoteSelector = false;
    let settings = getSettings();
    // if deleting current note, first switch to scratch note
    // TODO: maybe switch to the most recently opened
    if (name === settings.currentNoteName) {
      console.log("deleted current note, opening scratch note");
      await openNote(kScratchNoteName);
    }
    // must delete after openNote() because openNote() saves
    // current note
    await deleteNote(name);
    getEditor().focus();
    console.log("deleted note", name);
    // TODO: add a way to undo deletion of the note
    addToast(`Deleted note '${name}'`);
    logNoteOp("noteDelete");
  }

  /** @typedef {import("../editor/event.js").SelectionChangeEvent} SelectionChangeEvent */

  /**
   * @param {SelectionChangeEvent} e
   */
  function onCursorChange(e) {
    line = e.cursorLine.line;
    column = e.cursorLine.col;
    selectionSize = e.selectionSize;
    language = e.language;
    languageAuto = e.languageAuto;
  }

  function showHelpAsNote() {
    openNote(kHelpSystemNoteName);
  }

  function showReleaseNotes() {
    openNote(kReleaseNotesSystemNoteName);
  }

  function updateDocSize() {
    let editor = getEditor();
    const c = editor.getContent() || "";
    docSize = stringSizeInUtf8Bytes(c);
  }

  /**
   * @param {string} name
   */
  function didOpenNote(name) {
    console.log("didOpenNote:", name);
    throwIf(!name);
    noteName = name;
    console.log("onDocChanged: just opened");
    let readOnly = isSystemNoteName(name);
    editor.setReadOnly(readOnly);
    if (name === kDailyJournalNoteName) {
      console.log("journal, so going to next block");
      // editor.gotoNextBlock();
    }

    window.document.title = name;
    setURLHashNoReload(name);
    setSetting("currentNoteName", name);
    updateDocSize();
  }

  function docDidChange() {
    updateDocSize();
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="grid w-screen max-h-screen h-screen fixed grid-rows-[1fr_auto]"
  {oncontextmenu}
>
  <TopNav {noteName} shortcut={noteShortcut} {openNoteSelector} />
  <Editor
    cursorChange={onCursorChange}
    debugSyntaxTree={false}
    keymap={settings.keymap}
    emacsMetaKey={settings.emacsMetaKey}
    showLineNumberGutter={settings.showLineNumberGutter}
    showFoldGutter={settings.showFoldGutter}
    bracketClosing={settings.bracketClosing}
    fontFamily={settings.fontFamily}
    fontSize={settings.fontSize}
    bind:this={editor}
    {openLanguageSelector}
    {openHistorySelector}
    createNewScratchNote={createScratchNote}
    {openNoteSelector}
    {didOpenNote}
    {docDidChange}
  />
  <StatusBar
    shortcut={noteShortcut}
    {noteName}
    {line}
    {column}
    {docSize}
    {selectionSize}
    {language}
    {languageAuto}
    {isSpellChecking}
    {openLanguageSelector}
    {openNoteSelector}
    {formatCurrentBlock}
    {runCurrentBlock}
    {toggleSpellCheck}
    {openSettings}
  />
</div>

{#if showingNoteSelector}
  <Overlay klass="" onclose={closeNoteSelector}>
    <NoteSelector
      openNote={onOpenNote}
      createNote={onCreateNote}
      deleteNote={onDeleteNote}
    />
  </Overlay>
{/if}

<div class="overlay">
  {#if showingLanguageSelector}
    <LanguageSelector
      selectLanguage={onSelectLanguage}
      close={closeLanguageSelector}
    />
  {/if}
  {#if showingHistorySelector}
    <History close={closeHistorySelector} selectHistory={onSelectHistory} />
  {/if}
</div>

{#if loadingNoteName}
  <Loading {loadingNoteName} />
{/if}

{#if showingRenameNote}
  <Overlay onclose={closeRename}>
    <RenameNote rename={onRename} oldName={noteName} />
  </Overlay>
{/if}

{#if showingSettings}
  <Settings close={closeSettings}></Settings>
{/if}
<Toaster></Toaster>

{#if showingMenu}
  <Overlay
    onclose={closeMenu}
    klass="absolute cursor-pointer select-none"
    style={contextMenuStyle}
  >
    <Menu nest={1} {menuItemStatus} {onmenucmd} menu={contextMenu} />
  </Overlay>
{/if}
