// src/components/Settings.svelte
<script>
  import {
    kDefaultFontFamily,
    kDefaultFontSize,
    getVersion,
    saveSettings,
    setSetting,
    getSettings,
  } from "../settings";
  import { platform } from "../util";
  import { focus } from "../actions";

  /** @type {{
    close: () => void,
}}*/
  let { close } = $props();

  let keymaps = [
    { name: "Default", value: "default" },
    { name: "Emacs", value: "emacs" },
  ];

  let isMac = platform.isMac;

  let initialSettings = getSettings();
  let keymap = $state(initialSettings.keymap);
  let metaKey = $state(initialSettings.emacsMetaKey);
  let showLineNumberGutter = $state(initialSettings.showLineNumberGutter);
  let showFoldGutter = $state(initialSettings.showFoldGutter);
  let bracketClosing = $state(initialSettings.bracketClosing);
  let fontFamily = $state(initialSettings.fontFamily || kDefaultFontFamily);
  let fontSize = $state(initialSettings.fontSize || kDefaultFontSize);
  let theme = $state(initialSettings.theme);

  // console.log("fontFamily:", initialSettings.fontFamily);

  let defFont = [kDefaultFontFamily, kDefaultFontFamily + " (default)"];
  let systemFonts = $state([defFont]);
  let themes = [
    ["system", "System"],
    ["light", "Light"],
    ["dark", "Dark"],
  ];

  let defaultFontSize = $state(kDefaultFontSize);
  let appVersion = getVersion();
  let currentNoteName = initialSettings.currentNoteName;

  /** @type {HTMLElement} */
  let container;
  /** @type {HTMLElement} */
  let keymapSelector;

  let fontSizes = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
  $effect(() => {
    updateLocalFonts();
    if (container) {
      container.focus();
    }
    if (keymapSelector) {
      keymapSelector.focus();
    }
    window.addEventListener("keydown", onkeydown);
    return () => {
      window.removeEventListener("keydown", onkeydown);
    };
  });

  async function updateLocalFonts() {
    // @ts-ignore
    let qlf = window.queryLocalFonts;
    if (!qlf) {
      return;
    }
    let a = [defFont];
    let fonts = await qlf();
    let seen = []; // queryLocalFonts() returns duplicates
    for (let f of fonts) {
      /** @type {string} */
      let fam = f.family;
      if (fam === kDefaultFontFamily) {
        continue;
      }
      if (seen.includes(fam)) {
        continue;
      }
      // console.log("fam:", fam);
      a.push([fam, fam]);
      seen.push(fam);
    }
    systemFonts = a;
  }

  /**
   * @param {KeyboardEvent} ev
   */
  function onkeydown(ev) {
    let key = ev.key;
    if (key === "Escape") {
      ev.preventDefault();
      ev.stopImmediatePropagation();
      close();
      return;
    }
  }

  function updateTheme() {
    console.log("updateTheme", theme);
    //$emit("setTheme", theme);
    setSetting("theme", theme);
  }

  function updateSettings() {
    saveSettings({
      bracketClosing: bracketClosing,
      currentNoteName: currentNoteName,
      emacsMetaKey: platform.isMac ? metaKey : "alt",
      fontFamily: fontFamily === kDefaultFontFamily ? undefined : fontFamily,
      fontSize: fontSize === kDefaultFontSize ? undefined : fontSize,
      keymap: keymap,
      showFoldGutter: showFoldGutter,
      showLineNumberGutter: showLineNumberGutter,
      theme: theme,
    });
  }
</script>

<div class="fixed inset-0">
  <div class=" absolute inset-0 z-10 bg-black opacity-50 dark:opacity-20"></div>

  <div
    class="selector absolute overflow-auto center-x-with-translate top-[2rem] z-20 flex flex-col max-w-full px-4 py-4 max-h-[94vh] select-none"
  >
    <div>
      <h2>Input settings</h2>
      <label>
        <input
          use:focus
          type="checkbox"
          bind:checked={bracketClosing}
          onchange={updateSettings}
        />
        Auto-close brackets and quotation marks
      </label>
    </div>

    <div class="mt-2 flex flex-col">
      <h2>Gutters</h2>
      <label>
        <input
          type="checkbox"
          bind:checked={showLineNumberGutter}
          onchange={updateSettings}
        />
        Show line numbers
      </label>

      <label>
        <input
          type="checkbox"
          bind:checked={showFoldGutter}
          onchange={updateSettings}
        />
        Show fold gutter
      </label>
    </div>

    <div class="mt-2 flex justify-between">
      <h2>Keymap</h2>
      <select
        bind:this={keymapSelector}
        bind:value={keymap}
        onchange={updateSettings}
      >
        {#each keymaps as km (km.value)}
          <option selected={km.value === keymap} value={km.value}
            >{km.name}</option
          >
        {/each}
      </select>
    </div>

    {#if true || (keymap == "emacs" && isMac)}
      <div class="mt-2 flex justify-between">
        <h2>Meta Key</h2>
        <select bind:value={metaKey} onchange={updateSettings}>
          <option selected={metaKey === "meta"} value="meta">Command</option>
          <option selected={metaKey === "alt"} value="alt">Option</option>
        </select>
      </div>
    {/if}

    <div class="mt-2 flex justify-between">
      <h2>Font Family</h2>
      <select bind:value={fontFamily} onchange={updateSettings}>
        {#each systemFonts as font}
          {@const family = font[0]}
          {@const label = font[1]}
          <option selected={family === fontFamily} value={family}
            >{label}
          </option>
        {/each}
      </select>
    </div>

    <div class="mt-2 flex justify-between">
      <h2>Font Size</h2>
      <select bind:value={fontSize} onchange={updateSettings}>
        {#each fontSizes as size}
          <option selected={size === fontSize} value={size}
            >{size}px{size === defaultFontSize ? " (default)" : ""}</option
          >
        {/each}
      </select>
    </div>

    <div class="mt-2 flex justify-between">
      <h2>Theme</h2>
      <select bind:value={theme} onchange={updateTheme}>
        {#each themes as t}
          {@const th = t[0]}
          {@const label = t[1]}
          <option selected={th === theme} value={th}>{label} </option>
        {/each}
      </select>
    </div>

    <div class="mt-4 flex text-gray-400">
      Current Version: {appVersion}
    </div>

    <button
      tabindex="-1"
      class="mt-2 self-end border border-black dark:border-gray-400 px-4 py-1 hover:bg-gray-100 dark:hover:bg-gray-600"
      onclick={close}>Close</button
    >
  </div>
</div>

<style>
  select {
    @apply w-[200px];
    @apply ml-4;
    @apply border;
    @apply border-black;
    @apply px-2 py-1;
  }

  option {
    @apply px-2 py-2;
  }
  h2 ~ label {
    margin-left: 4px;
  }

  label > input[type="checkbox"] {
    position: relative;
    top: 2px;
    left: -3px;
  }
  h2 {
    @apply font-bold;
  }
</style>

// src/components/settings/Settings.vue
<script>
import TabListItem from "./TabListItem.vue"
import TabContent from "./TabContent.vue"
import { kDefaultFontFamily, kDefaultFontSize, getVersion, saveSettings, setSetting } from "../../settings"
import { platform } from "../../util"

export default {
  props: {
    initialKeymap: String,
    initialSettings: Object,
  },
  components: {
    TabListItem,
    TabContent,
  },

  data() {
    return {
      keymaps: [
        { name: "Default", value: "default" },
        { name: "Emacs", value: "emacs" },
      ],
      keymap: this.initialSettings.keymap,
      metaKey: this.initialSettings.emacsMetaKey,
      isMac: platform.isMac,
      showLineNumberGutter: this.initialSettings.showLineNumberGutter,
      showFoldGutter: this.initialSettings.showFoldGutter,
      bracketClosing: this.initialSettings.bracketClosing,
      fontFamily: this.initialSettings.fontFamily || kDefaultFontFamily,
      fontSize: this.initialSettings.fontSize || kDefaultFontSize,
      theme: this.initialSettings.theme,

      activeTab: "general",
      systemFonts: [[kDefaultFontFamily, kDefaultFontFamily + " (default)"]],
      themes: [["system", "System"], ["light", "Light"], ["dark", "Dark"]],
      defaultFontSize: kDefaultFontSize,
      appVersion: "",
      currentNoteName: this.initialSettings.currentNoteName,

      lastTheme: this.initialSettings.theme,
    }
  },

  async mounted() {
    // @ts-ignore
    let qlf = window.queryLocalFonts;
    if (qlf !== undefined) {
      let localFonts = [... new Set((await qlf()).map(f => f.family))].filter(f => f !== kDefaultFontFamily)
      localFonts = [...new Set(localFonts)].map(f => [f, f])
      this.systemFonts = [[kDefaultFontFamily, kDefaultFontFamily + " (default)"], ...localFonts]
    }

    window.addEventListener("keydown", this.onKeyDown);
    // @ts-ignore
    this.$refs.keymapSelector.focus()

    this.appVersion = getVersion()
  },
  beforeUnmount() {
    window.removeEventListener("keydown", this.onKeyDown);
  },

  methods: {
    /**
     * @param {KeyboardEvent} event
     */
    onKeyDown(event) {
      let key = event.key;

      if (key === "Escape") {
        event.preventDefault()
        event.stopImmediatePropagation()
        this.$emit("close")
        return;
      }
    },

    updateTheme() {
      console.log("updateTheme", this.theme)
      this.$emit("setTheme", this.theme)
      setSetting("theme", this.theme)
    },

    updateSettings() {
      saveSettings({
        bracketClosing: this.bracketClosing,
        currentNoteName: this.currentNoteName,
        emacsMetaKey: platform.isMac ? this.metaKey : "alt",
        fontFamily: this.fontFamily === kDefaultFontFamily ? undefined : this.fontFamily,
        fontSize: this.fontSize === kDefaultFontSize ? undefined : this.fontSize,
        keymap: this.keymap,
        showFoldGutter: this.showFoldGutter,
        showLineNumberGutter: this.showLineNumberGutter,
        theme: this.theme,
      })
    },
  }
}
</script>

<template>
  <div class="fixed inset-0">
    <div
      class="dialog gray-700 absolute top-[2rem] z-20 flex flex-col bg-white max-w-full max-h-full rounded shadow-xl w-[640px] h-[460px] center-x-with-translate overflow-y-auto no-border-outline">
      <div class="flex grow">
        <nav class="sidebar w-[140px] pt-[20px] border-r border-gray-300 border-solid">
          <h1 class="text-[16px] font-bold mb-[20px] py-0 px-[20px]">Settings</h1>
          <ul>
            <TabListItem name="General" tab="general" :activeTab="activeTab" @click="activeTab = 'general'" />
            <TabListItem name="Editing" tab="editing" :activeTab="activeTab" @click="activeTab = 'editing'" />
            <TabListItem name="Appearance" tab="appearance" :activeTab="activeTab" @click="activeTab = 'appearance'" />
            <TabListItem name="Version" tab="updates" :activeTab="activeTab" @click="activeTab = 'updates'" />
          </ul>
        </nav>
        <div class="settings-content flex-grow overflow-y-auto p-[40px]">
          <TabContent tab="general" :activeTab="activeTab">
            <div class="row">
              <div class="entry">
                <h2>Keymap</h2>
                <select ref="keymapSelector" v-model="keymap" @change="updateSettings"
                  class="keymap border border-black">
                  <template v-for="km in keymaps" :key="km.value">
                    <option :selected="km.value === keymap" :value="km.value">{{ km.name }}</option>
                  </template>
                </select>
              </div>
              <div class="entry" v-if="keymap === 'emacs' && isMac">
                <h2>Meta Key</h2>
                <select v-model="metaKey" @change="updateSettings" class="metaKey border border-black">
                  <option :selected="metaKey === 'meta'" value="meta">Command</option>
                  <option :selected="metaKey === 'alt'" value="alt">Option</option>
                </select>
              </div>
            </div>
          </TabContent>

          <TabContent tab="editing" :activeTab="activeTab">
            <div class="row">
              <div class="entry">
                <h2>Input settings</h2>
                <label>
                  <input type="checkbox" v-model="bracketClosing" @change="updateSettings" />
                  Auto-close brackets and quotation marks
                </label>
              </div>
            </div>
          </TabContent>

          <TabContent tab="appearance" :activeTab="activeTab">
            <div class="row flex">
              <div class="entry">
                <h2>Gutters</h2>
                <label>
                  <input type="checkbox" v-model="showLineNumberGutter" @change="updateSettings" />
                  Show line numbers
                </label>

                <label>
                  <input type="checkbox" v-model="showFoldGutter" @change="updateSettings" />
                  Show fold gutter
                </label>
              </div>
            </div>
            <div class="row flex">
              <div class="entry">
                <h2>Theme</h2>
                <select v-model="theme" @change="updateTheme" class="width-[280px] border border-black">
                  <option v-for="[theme, label] in themes" :selected="theme === this.theme" :value="theme">{{ label }}
                  </option>
                </select>
              </div>
            </div>
            <div class="row flex">
              <div class="entry">
                <h2>Font Family</h2>
                <select v-model="fontFamily" @change="updateSettings" class="width-[280px] border border-black">
                  <option v-for="[font, label] in systemFonts" :selected="font === fontFamily" :value="font">{{ label }}
                  </option>
                </select>
              </div>
              <div class="entry">
                <h2>Font Size</h2>
                <select v-model="fontSize" @change="updateSettings" class="width-[120px] border border-black">
                  <option v-for="size in [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]"
                    :selected="size === fontSize" :value="size">{{ size }}px{{ size ===
              defaultFontSize ? " (default)" : "" }}</option>
                </select>
              </div>
            </div>
          </TabContent>

          <TabContent tab="updates" :activeTab="activeTab">
            <div class="row">
              <div class="entry">
                <h2>Current Version</h2>
                <b>{{ appVersion }}</b>
              </div>
            </div>
          </TabContent>
        </div>
      </div>

      <div class="bottom-bar text-right py-[10px] px-[20px] bg-gray-100">
        <button @click="$emit('close')" class="close border-gray-500 px-4 border">Close</button>
      </div>
    </div>
    <div class="bg-black opacity-50 absolute inset-0 z-10"></div>
  </div>
</template>

<style scoped>
html[theme=dark] .dialog {
  background: #333;
  color: #eee;
  box-shadow: 0 0 25px rgba(0, 0, 0, 0.3);
}

html[theme=dark] .sidebar {
  border-right: 1px solid #222;
}

.settings-content select {
  height: 22px;
}

html[theme=dark] .settings-content select {
  background: #222;
  color: #eee;
}

.settings-content .row {
  display: flex;
}

.settings-content .row .entry {
  margin-bottom: 24px;
  margin-right: 20px;
}

.settings-content .row .entry:last-child {
  margin-right: 0;
}

.settings-content .row .entry h2 {
  font-weight: 600;
  margin-bottom: 10px;
  font-size: 14px;
}

.settings-content .row .entry select {
  width: 200px;
}

.settings-content .row .entry select:focus {
  outline: none;
}

.settings-content .row .entry label {
  display: block;
  user-select: none;
}

.settings-content .row .entry label>input[type=checkbox] {
  position: relative;
  top: 2px;
  left: -3px;
}

html[theme=dark] .bottom-bar {
  background: #222;
}

.bottom-bar .close {
  height: 28px;
}

.bottom-bar .close:hover {
  background-color: lightgray;
}

html[theme=dark] .bottom-bar .close:hover {
  background: #333;
  color: #eee;
}
</style>
